# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/standard-model',
                'doc_host': 'https://xrsrke.github.io',
                'git_url': 'https://github.com/xrsrke/standard-model',
                'lib_path': 'standard_model'},
  'syms': { 'standard_model.core': {'standard_model.core.foo': ('core.html#foo', 'standard_model/core.py')},
            'standard_model.elementary_particle': { 'standard_model.elementary_particle.ElementaryParticle': ( 'elementary_particle.html#elementaryparticle',
                                                                                                               'standard_model/elementary_particle.py'),
                                                    'standard_model.elementary_particle.ElementaryParticle.__init__': ( 'elementary_particle.html#__init__',
                                                                                                                        'standard_model/elementary_particle.py')},
            'standard_model.force': {'standard_model.force.Force': ('force.html#force', 'standard_model/force.py')}}}