# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/02_force.ipynb.

# %% auto 0
__all__ = ['Force']

# %% ../nbs/02_force.ipynb 4
class Force:
    FORCE_CLASSIFICATION = ("elelectromagnetic", "strong", "weak", "gravity")
    pass
